set lines =999 "Go maximized!"
set columns =999
set visualbell " Keeps the audio bell from sounding in the GUI
set go -=mTrLb
"remove gui bars
set guioptions -=m "menubar"
set guioptions -=T "Toolbar"
set guioptions -=r "right scrollbar"
set guioptions -=L "Left scrollbar"
set guioptions -=b "bottom scrollbar"
"fonts
set guifont=*
